// <auto-generated />
using System;
using Desafio_Psychometrika.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio_Psychometrika.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20231226003818_Db_Psychometrika")]
    partial class Db_Psychometrika
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Desafio_Psychometrika.Models.Gabarito", b =>
                {
                    b.Property<Guid>("GabaritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProvaSimuladoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestoesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RespostaCorreta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GabaritoId");

                    b.ToTable("Gabaritos");
                });

            modelBuilder.Entity("Desafio_Psychometrika.Models.ProvaSimulado", b =>
                {
                    b.Property<Guid>("ProvaSimuladoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProvaNome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProvaSimuladoId");

                    b.ToTable("ProvaSimulados");
                });

            modelBuilder.Entity("Desafio_Psychometrika.Models.Questoes", b =>
                {
                    b.Property<Guid>("QuestoesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Questao")
                        .HasColumnType("int");

                    b.HasKey("QuestoesId");

                    b.ToTable("Questoes");
                });

            modelBuilder.Entity("Desafio_Psychometrika.Models.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Desafio_Psychometrika.Models.UsuarioProva", b =>
                {
                    b.Property<Guid>("UsuarioProvaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProvaSimuladoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestoesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Respondido")
                        .HasColumnType("bit");

                    b.Property<int?>("Resposta")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioProvaId");

                    b.ToTable("UsuarioProvas");
                });
#pragma warning restore 612, 618
        }
    }
}
